"""initial schema

Revision ID: 55f1d1b0dcda
Revises: 
Create Date: 2026-05-24 23:15:15.108297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f1d1b0dcda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'completed', name='schedule_status'), nullable=False),
    sa.Column('batch_job_id', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_schedule')),
    sa.UniqueConstraint('date', name=op.f('uq_daily_schedule_date'))
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_table('question_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_type'))
    )
    op.create_table('topic_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_type'))
    )
    op.create_table('topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('topic_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_type_id'], ['topic_type.id'], name=op.f('fk_topic_topic_type_id_topic_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic'))
    )
    op.create_table('daily_topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_schedule_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['daily_schedule_id'], ['daily_schedule.id'], name=op.f('fk_daily_topic_daily_schedule_id_daily_schedule')),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_daily_topic_topic_id_topic')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_topic'))
    )
    op.create_table('question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('prior_question_id', sa.UUID(), nullable=True),
    sa.Column('daily_schedule_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_schedule_id'], ['daily_schedule.id'], name=op.f('fk_question_daily_schedule_id_daily_schedule')),
    sa.ForeignKeyConstraint(['prior_question_id'], ['question.id'], name=op.f('fk_question_prior_question_id_question')),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_type.id'], name=op.f('fk_question_question_type_id_question_type')),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_question_topic_id_topic')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_table('chat_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('daily_schedule_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['daily_schedule_id'], ['daily_schedule.id'], name=op.f('fk_chat_session_daily_schedule_id_daily_schedule')),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_chat_session_question_id_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session'))
    )
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('system', 'user_initial_answer', 'user', 'assistant', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_message_session_id_chat_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('chat_session')
    op.drop_table('question')
    op.drop_table('daily_topic')
    op.drop_table('topic')
    op.drop_table('topic_type')
    op.drop_table('question_type')
    op.drop_table('llm_usage')
    op.drop_table('daily_schedule')
    # ### end Alembic commands ###
